### ISSUE TITLE
cob_face_recognizer.launch on't show nothing

### ISSUE THREAD

**Issue by amalgmar12** [cagbal/ros_people_object_detection_tensorflow#34] opened 2018-08-16 12:08 UTC
Hi,

 this code seems interesting .I compiled it but when I run cob_face_recognizer.launch , it shows me images in database and after that it is blocked .Thank you for advance for your help 
![block](https://user-images.githubusercontent.com/37368595/44207504-6b57ac00-a155-11e8-9118-886004f718e3.png)

**Comment by cagbal** [comment] 2018-08-20 07:14
Hi sorry for late reply. This is an expected behavior. Could you check from Rviz whether there is a face detection image topic? Also, you should also check the topic named "/face_recognizer/faces". If there is a stream coming out, then there is no problem.

**Comment by amalgmar12** [comment] 2018-08-22 22:48
Ok , thank you for your help . I will see if the problem disappear

**Comment by amalgmar12** [comment] 2018-08-23 08:30
Hi,
I opened rviz and I add topic "/face_recognizer/faces/images" but there is no rgb stream coming on . Please Can you pretend what's the problem ?

**Comment by cagbal** [comment] 2018-08-23 08:48
I run the code on my local PC and there is an RGB stream coming out from "/face_recognizer/faces/image". So, I cannot further help, because everything seems normal and there is not so much information from your side.

**Comment by amalgmar12** [comment] 2018-08-23 11:07
I use openni version 1 for kinetic . I tested your code cob_people_detection and it's ok . I tried to change camera topics but no improvements .

**Comment by cagbal** [comment] 2018-08-23 11:44
There is nothing I can do at this point. Closing the issue.

**Closed by cagbal** 2018-08-23 11:44 UTC
